# Generated by Django 5.0 on 2023-12-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_number',
        ),
    ]
