# Generated by Django 5.0 on 2023-12-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/cover_default.jpg', height_field='cover_h', upload_to='covers/', width_field='cover_w'),
        ),
    ]
