# Generated by Django 5.0 on 2023-12-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_h',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_w',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
