# Generated by Django 5.0 on 2024-01-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_cover_h_book_cover_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='follows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='popularity_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='quality_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_w',
            field=models.IntegerField(default=0),
        ),
    ]
