# Generated by Django 5.0 on 2024-01-02 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_follows_book_popularity_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
